/* -*-H-*-
*******************************************************************************
* altobeam
* Reproduction and Communication of this document is strictly prohibited
* unless specifically authorized in writing by altobeam
******************************************************************************/
/**
* \file
* \ingroup PAS
*
* \brief General PAS WLAN Definitions
*/
/*
***************************************************************************
* Copyright altobeam, 2009 ?All rights reserved.
*
* This information, source code and any compilation or derivative thereof are
* the proprietary information of altobeam and/or its licensors and are
* confidential in nature. Under no circumstances is this software to be exposed
* to or placed under an Open Source License of any type without the expressed
* written permission of altobeam.
*
* Although care has been taken to ensure the accuracy of the information and the
* software, altobeam assumes no responsibility therefore.
*
* THE INFORMATION AND SOFTWARE ARE PROVIDED "AS IS" AND "AS AVAILABLE".
*
* altobeam MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OR MERCHANTABILITY, FITNESS
* FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS,
*
****************************
* Updates
* 16/04/2009 - WBF00003856 - http://cqweb.zav.st.com/cqweb/url/default.asp?db=WBF&id=WBF00003856
****************************************************************************/

#include "pac_defs.h"
#include "pac_regs.h"
#ifndef PAC_DEFS_WLAN_H
#define PAC_DEFS_WLAN_H

/* ----------------------------------------------------------------*/
/* ST - "PTCS pointer table" - Pg 49 - 11.4.4 */
#define PAC_PTCS_TABLE__AGGREND_RESPONDBA_MA_0          PAC_PTCS_TABLE__RX_EVENT_00
#define PAC_PTCS_TABLE__AGGREND_RESPONDBA_MA_1          PAC_PTCS_TABLE__RX_EVENT_01
#define PAC_PTCS_TABLE__AGGREND                         PAC_PTCS_TABLE__RX_EVENT_02
#define PAC_PTCS_TABLE__FRAME_ABORT                     PAC_PTCS_TABLE__RX_EVENT_03
#define PAC_PTCS_TABLE__CRC_ERROR                       PAC_PTCS_TABLE__RX_EVENT_04
#define PAC_PTCS_TABLE__RESERVED_1                      PAC_PTCS_TABLE__RX_EVENT_05
#define PAC_PTCS_TABLE__CTS                             PAC_PTCS_TABLE__RX_EVENT_06
#define PAC_PTCS_TABLE__RTS_MA_0                        PAC_PTCS_TABLE__RX_EVENT_07
#define PAC_PTCS_TABLE__RTS_MA_1                        PAC_PTCS_TABLE__RX_EVENT_08
#define PAC_PTCS_TABLE__BAR_IMM_MA_0                    PAC_PTCS_TABLE__RX_EVENT_09
#define PAC_PTCS_TABLE__BAR_IMM_MA_1                    PAC_PTCS_TABLE__RX_EVENT_10
#define PAC_PTCS_TABLE__BAR_DELAYED_NOACK               PAC_PTCS_TABLE__RX_EVENT_11
#define PAC_PTCS_TABLE__BA_IMM                          PAC_PTCS_TABLE__RX_EVENT_12
#define PAC_PTCS_TABLE__BA_DELAYED_NOACK                PAC_PTCS_TABLE__RX_EVENT_13
#define PAC_PTCS_TABLE__BSS_BEACON                      PAC_PTCS_TABLE__RX_EVENT_14
#define PAC_PTCS_TABLE__MULTICAST_PKT                   PAC_PTCS_TABLE__RX_EVENT_15
#define PAC_PTCS_TABLE__QOSDATA_NOACK                   PAC_PTCS_TABLE__RX_EVENT_16
#define PAC_PTCS_TABLE__ACK_RECD_SEND_NEXT_DATA         PAC_PTCS_TABLE__RX_EVENT_17
#define PAC_PTCS_TABLE__RESERVED_2                      PAC_PTCS_TABLE__RX_EVENT_18
#define PAC_PTCS_TABLE__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_PTCS_TABLE__RX_EVENT_19
#define PAC_PTCS_TABLE__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_PTCS_TABLE__RX_EVENT_20
#define PAC_PTCS_TABLE__QOSDATA_CLEARNAV                PAC_PTCS_TABLE__RX_EVENT_21
#define PAC_PTCS_TABLE__CFEND_RECD_CLEARNAV             PAC_PTCS_TABLE__RX_EVENT_22
#define PAC_PTCS_TABLE__NOT_FOR_US_UPDATENAV            PAC_PTCS_TABLE__RX_EVENT_23

/* ----------------------------------------------------------------*/
/* ST - "Rx event response enable" - Pg 52 | Tality - "rx_event_resp_enable" - 1.9.2 */
#define PAC_NTD_RX_EVT_RSP_EN__AGGREND_RESPONDBA_MA_0          PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_00
#define PAC_NTD_RX_EVT_RSP_EN__AGGREND_RESPONDBA_MA_1          PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_01
#define PAC_NTD_RX_EVT_RSP_EN__AGGREND                         PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_02
#define PAC_NTD_RX_EVT_RSP_EN__FRAME_ABORT                     PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_03
#define PAC_NTD_RX_EVT_RSP_EN__CRC_ERROR                       PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_04
#define PAC_NTD_RX_EVT_RSP_EN__RESERVED_1                      PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_05
#define PAC_NTD_RX_EVT_RSP_EN__CTS                             PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_06
#define PAC_NTD_RX_EVT_RSP_EN__RTS_MA_0                        PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_07
#define PAC_NTD_RX_EVT_RSP_EN__RTS_MA_1                        PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_08
#define PAC_NTD_RX_EVT_RSP_EN__BAR_IMM_MA_0                    PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_09
#define PAC_NTD_RX_EVT_RSP_EN__BAR_IMM_MA_1                    PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_10
#define PAC_NTD_RX_EVT_RSP_EN__BAR_DELAYED_NOACK               PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_11
#define PAC_NTD_RX_EVT_RSP_EN__BA_IMM                          PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_12
#define PAC_NTD_RX_EVT_RSP_EN__BA_DELAYED_NOACK                PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_13
#define PAC_NTD_RX_EVT_RSP_EN__BSS_BEACON                      PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_14
#define PAC_NTD_RX_EVT_RSP_EN__MULTICAST_PKT                   PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_15
#define PAC_NTD_RX_EVT_RSP_EN__QOSDATA_NOACK                   PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_16
#define PAC_NTD_RX_EVT_RSP_EN__ACK_RECD_SEND_NEXT_DATA         PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_17
#define PAC_NTD_RX_EVT_RSP_EN__RESERVED_2                      PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_18
#define PAC_NTD_RX_EVT_RSP_EN__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_19
#define PAC_NTD_RX_EVT_RSP_EN__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_20
#define PAC_NTD_RX_EVT_RSP_EN__QOSDATA_CLEARNAV                PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_21
#define PAC_NTD_RX_EVT_RSP_EN__CFEND_RECD_CLEARNAV             PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_22
#define PAC_NTD_RX_EVT_RSP_EN__NOT_FOR_US_UPDATENAV            PAC_NTD_RX_EVT_RSP_EN__RX_EVENT_23

//PAC_NTD_RX_EVT_RSP_EN__RESPONSE_TIMEOUT_A
//PAC_NTD_RX_EVT_RSP_EN__RESPONSE_TIMEOUT_B

/* ----------------------------------------------------------------*/
/* ST - "Rx event response multi-shot" - Pg 53 (section number missing) | Tality - "rx_event_resp_multi_shot" - 1.9.3 */
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__AGGREND_RESPONDBA_MA_0          PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_00
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__AGGREND_RESPONDBA_MA_1          PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_01
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__AGGREND                         PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_02
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__FRAME_ABORT                     PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_03
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__CRC_ERROR                       PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_04
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__RESERVED_1                      PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_05
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__CTS                             PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_06
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__RTS_MA_0                        PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_07
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__RTS_MA_1                        PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_08
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__BAR_IMM_MA_0                    PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_09
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__BAR_IMM_MA_1                    PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_10
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__BAR_DELAYED_NOACK               PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_11
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__BA_IMM                          PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_12
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__BA_DELAYED_NOACK                PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_13
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__BSS_BEACON                      PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_14
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__MULTICAST_PKT                   PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_15
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__QOSDATA_NOACK                   PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_16
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__ACK_RECD_SEND_NEXT_DATA         PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_17
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__RESERVED_2                      PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_18
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_19
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_20
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__QOSDATA_CLEARNAV                PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_21
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__CFEND_RECD_CLEARNAV             PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_22
#define PAC_NTD_RX_EVT_RSP_MULTISHOT__NOT_FOR_US_UPDATENAV            PAC_NTD_RX_EVT_RSP_MULTISHOT__RX_EVENT_23
//PAC_NTD_RX_EVT_RSP_MULTISHOT__RESPONSE_TIMEOUT

/* ----------------------------------------------------------------*/
/* NTD Status [5:0] */
#define PAC_NTD_STATUS__AGGREND_RESPONDBA_MA_0          PAC_NTD_STATUS__RX_EVENT_00
#define PAC_NTD_STATUS__AGGREND_RESPONDBA_MA_1          PAC_NTD_STATUS__RX_EVENT_01
#define PAC_NTD_STATUS__AGGREND                         PAC_NTD_STATUS__RX_EVENT_02
#define PAC_NTD_STATUS__FRAME_ABORT                     PAC_NTD_STATUS__RX_EVENT_03
#define PAC_NTD_STATUS__CRC_ERROR                       PAC_NTD_STATUS__RX_EVENT_04
#define PAC_NTD_STATUS__RESERVED_1                      PAC_NTD_STATUS__RX_EVENT_05
#define PAC_NTD_STATUS__CTS                             PAC_NTD_STATUS__RX_EVENT_06
#define PAC_NTD_STATUS__RTS_MA_0                        PAC_NTD_STATUS__RX_EVENT_07
#define PAC_NTD_STATUS__RTS_MA_1                        PAC_NTD_STATUS__RX_EVENT_08
#define PAC_NTD_STATUS__BAR_IMM_MA_0                    PAC_NTD_STATUS__RX_EVENT_09
#define PAC_NTD_STATUS__BAR_IMM_MA_1                    PAC_NTD_STATUS__RX_EVENT_10
#define PAC_NTD_STATUS__BAR_DELAYED_NOACK               PAC_NTD_STATUS__RX_EVENT_11
#define PAC_NTD_STATUS__BA_IMM                          PAC_NTD_STATUS__RX_EVENT_12
#define PAC_NTD_STATUS__BA_DELAYED_NOACK                PAC_NTD_STATUS__RX_EVENT_13
#define PAC_NTD_STATUS__BSS_BEACON                      PAC_NTD_STATUS__RX_EVENT_14
#define PAC_NTD_STATUS__MULTICAST_PKT                   PAC_NTD_STATUS__RX_EVENT_15
#define PAC_NTD_STATUS__QOSDATA_NOACK                   PAC_NTD_STATUS__RX_EVENT_16
#define PAC_NTD_STATUS__ACK_RECD_SEND_NEXT_DATA         PAC_NTD_STATUS__RX_EVENT_17
#define PAC_NTD_STATUS__RESERVED_2                      PAC_NTD_STATUS__RX_EVENT_18
#define PAC_NTD_STATUS__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_NTD_STATUS__RX_EVENT_19
#define PAC_NTD_STATUS__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_NTD_STATUS__RX_EVENT_20
#define PAC_NTD_STATUS__QOSDATA_CLEARNAV                PAC_NTD_STATUS__RX_EVENT_21
#define PAC_NTD_STATUS__CFEND_RECD_CLEARNAV             PAC_NTD_STATUS__RX_EVENT_22
#define PAC_NTD_STATUS__NOT_FOR_US_UPDATENAV            PAC_NTD_STATUS__RX_EVENT_23
#define PAC_NTD_STATUS__RESPONSE_TIMEOUT                PAC_NTD_STATUS__RX_EVENT_RESPONSE_TIMEOUT
#define PAC_NTD_STATUS__UNRECOGNISEDRX                  PAC_NTD_STATUS__RX_EVENT_UNRECOGNISEDRX

/* NTD Status - PTCS Status - Request [13:8] */
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__AGGREND_RESPONDBA_MA_0          PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_00
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__AGGREND_RESPONDBA_MA_1          PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_01
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__AGGREND                         PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_02
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__FRAME_ABORT                     PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_03
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__CRC_ERROR                       PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_04
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__RESERVED_1                      PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_05
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__CTS                             PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_06
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__RTS_MA_0                        PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_07
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__RTS_MA_1                        PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_08
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__BAR_IMM_MA_0                    PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_09
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__BAR_IMM_MA_1                    PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_10
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__BAR_DELAYED_NOACK               PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_11
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__BA_IMM                          PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_12
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__BA_DELAYED_NOACK                PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_13
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__BSS_BEACON                      PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_14
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__MULTICAST_PKT                   PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_15
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__QOSDATA_NOACK                   PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_16
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__ACK_RECD_SEND_NEXT_DATA         PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_17
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__RESERVED_2                      PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_18
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_19
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_20
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__QOSDATA_CLEARNAV                PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_21
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__CFEND_RECD_CLEARNAV             PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_22
#define PAC_NTD_STATUS__PTCS_REQUEST__HIGH__NOT_FOR_US_UPDATENAV            PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_HIGH_23
//PAC_NTD_STATUS__PTCS_REQUEST__TSF_HW_EVENT_0
//PAC_NTD_STATUS__PTCS_REQUEST__TSF_HW_EVENT_1
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__AGGREND_RESPONDBA_MA_0          PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_00
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__AGGREND_RESPONDBA_MA_1          PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_01
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__AGGREND                         PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_02
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__FRAME_ABORT                     PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_03
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__CRC_ERROR                       PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_04
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__RESERVED_1                      PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_05
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__CTS                             PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_06
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__RTS_MA_0                        PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_07
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__RTS_MA_1                        PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_08
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__BAR_IMM_MA_0                    PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_09
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__BAR_IMM_MA_1                    PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_10
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__BAR_DELAYED_NOACK               PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_11
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__BA_IMM                          PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_12
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__BA_DELAYED_NOACK                PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_13
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__BSS_BEACON                      PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_14
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__MULTICAST_PKT                   PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_15
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__QOSDATA_NOACK                   PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_16
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__ACK_RECD_SEND_NEXT_DATA         PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_17
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__RESERVED_2                      PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_18
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_19
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_20
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__QOSDATA_CLEARNAV                PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_21
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__CFEND_RECD_CLEARNAV             PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_22
#define PAC_NTD_STATUS__PTCS_REQUEST__LOW__NOT_FOR_US_UPDATENAV            PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_23
//PAC_NTD_STATUS__PTCS_REQUEST__RX_EVENT_LOW_RESPONSE_TIMEOUT 52
//PAC_NTD_STATUS__PTCS_REQUEST__SW_TX_REQUEST_0
//PAC_NTD_STATUS__PTCS_REQUEST__SW_TX_REQUEST_1
//PAC_NTD_STATUS__PTCS_REQUEST__EBM_SEQ_REQ
//PAC_NTD_STATUS__PTCS_REQUEST__IDLE


/* ----------------------------------------------------------------*/
/* ST - NTD: "Rx SW event enable" - Pg 55 | Tality - "rx_sw_event_enable" - 1.9.8 */
#define PAC_NTD_RX_SW_EVT_EN__AGGREND_RESPONDBA_MA_0          PAC_NTD_RX_SW_EVT_EN__RX_EVENT_00
#define PAC_NTD_RX_SW_EVT_EN__AGGREND_RESPONDBA_MA_1          PAC_NTD_RX_SW_EVT_EN__RX_EVENT_01
#define PAC_NTD_RX_SW_EVT_EN__AGGREND                         PAC_NTD_RX_SW_EVT_EN__RX_EVENT_02
#define PAC_NTD_RX_SW_EVT_EN__FRAME_ABORT                     PAC_NTD_RX_SW_EVT_EN__RX_EVENT_03
#define PAC_NTD_RX_SW_EVT_EN__CRC_ERROR                       PAC_NTD_RX_SW_EVT_EN__RX_EVENT_04
#define PAC_NTD_RX_SW_EVT_EN__RESERVED_1                      PAC_NTD_RX_SW_EVT_EN__RX_EVENT_05
#define PAC_NTD_RX_SW_EVT_EN__CTS                             PAC_NTD_RX_SW_EVT_EN__RX_EVENT_06
#define PAC_NTD_RX_SW_EVT_EN__RTS_MA_0                        PAC_NTD_RX_SW_EVT_EN__RX_EVENT_07
#define PAC_NTD_RX_SW_EVT_EN__RTS_MA_1                        PAC_NTD_RX_SW_EVT_EN__RX_EVENT_08
#define PAC_NTD_RX_SW_EVT_EN__BAR_IMM_MA_0                    PAC_NTD_RX_SW_EVT_EN__RX_EVENT_09
#define PAC_NTD_RX_SW_EVT_EN__BAR_IMM_MA_1                    PAC_NTD_RX_SW_EVT_EN__RX_EVENT_10
#define PAC_NTD_RX_SW_EVT_EN__BAR_DELAYED_NOACK               PAC_NTD_RX_SW_EVT_EN__RX_EVENT_11
#define PAC_NTD_RX_SW_EVT_EN__BA_IMM                          PAC_NTD_RX_SW_EVT_EN__RX_EVENT_12
#define PAC_NTD_RX_SW_EVT_EN__BA_DELAYED_NOACK                PAC_NTD_RX_SW_EVT_EN__RX_EVENT_13
#define PAC_NTD_RX_SW_EVT_EN__BSS_BEACON                      PAC_NTD_RX_SW_EVT_EN__RX_EVENT_14
#define PAC_NTD_RX_SW_EVT_EN__MULTICAST_PKT                   PAC_NTD_RX_SW_EVT_EN__RX_EVENT_15
#define PAC_NTD_RX_SW_EVT_EN__QOSDATA_NOACK                   PAC_NTD_RX_SW_EVT_EN__RX_EVENT_16
#define PAC_NTD_RX_SW_EVT_EN__ACK_RECD_SEND_NEXT_DATA         PAC_NTD_RX_SW_EVT_EN__RX_EVENT_17
#define PAC_NTD_RX_SW_EVT_EN__RESERVED_2                      PAC_NTD_RX_SW_EVT_EN__RX_EVENT_18
#define PAC_NTD_RX_SW_EVT_EN__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_NTD_RX_SW_EVT_EN__RX_EVENT_19
#define PAC_NTD_RX_SW_EVT_EN__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_NTD_RX_SW_EVT_EN__RX_EVENT_20
#define PAC_NTD_RX_SW_EVT_EN__QOSDATA_CLEARNAV                PAC_NTD_RX_SW_EVT_EN__RX_EVENT_21
#define PAC_NTD_RX_SW_EVT_EN__CFEND_RECD_CLEARNAV             PAC_NTD_RX_SW_EVT_EN__RX_EVENT_22
#define PAC_NTD_RX_SW_EVT_EN__NOT_FOR_US_UPDATENAV            PAC_NTD_RX_SW_EVT_EN__RX_EVENT_23
#define PAC_NTD_RX_SW_EVT_EN__RESPONSE_TIMEOUT                PAC_NTD_RX_SW_EVT_EN__RX_EVENT_RESPONSE_TIMEOUT
#define PAC_NTD_RX_SW_EVT_EN__UNRECOGNISEDRX                  PAC_NTD_RX_SW_EVT_EN__RX_EVENT_UNRECOGNISEDRX
#define PAC_NTD_RX_SW_EVT_EN__DISABLE_ALL                     (0)

#define PAC_NTD_RX_SW_EVT_EN__DEFAULT_VALUE                 \
    ( PAC_NTD_RX_SW_EVT_EN__AGGREND_RESPONDBA_MA_0          \
    | PAC_NTD_RX_SW_EVT_EN__AGGREND_RESPONDBA_MA_1          \
    | PAC_NTD_RX_SW_EVT_EN__AGGREND                         \
    | PAC_NTD_RX_SW_EVT_EN__CTS                             \
    | PAC_NTD_RX_SW_EVT_EN__RTS_MA_0                        \
    | PAC_NTD_RX_SW_EVT_EN__RTS_MA_1                        \
    | PAC_NTD_RX_SW_EVT_EN__BAR_IMM_MA_0                    \
    | PAC_NTD_RX_SW_EVT_EN__BAR_IMM_MA_1                    \
    | PAC_NTD_RX_SW_EVT_EN__BAR_DELAYED_NOACK               \
    | PAC_NTD_RX_SW_EVT_EN__BA_IMM                          \
    | PAC_NTD_RX_SW_EVT_EN__BA_DELAYED_NOACK                \
    | PAC_NTD_RX_SW_EVT_EN__BSS_BEACON                      \
    | PAC_NTD_RX_SW_EVT_EN__MULTICAST_PKT                   \
    | PAC_NTD_RX_SW_EVT_EN__QOSDATA_NOACK                   \
    | PAC_NTD_RX_SW_EVT_EN__ACK_RECD_SEND_NEXT_DATA         \
    | PAC_NTD_RX_SW_EVT_EN__UNICAST_PKT_RECD_SEND_ACK_MA_0  \
    | PAC_NTD_RX_SW_EVT_EN__UNICAST_PKT_RECD_SEND_ACK_MA_1  \
    | PAC_NTD_RX_SW_EVT_EN__RESPONSE_TIMEOUT                \
    | PAC_NTD_RX_SW_EVT_EN__UNRECOGNISEDRX )

/* ----------------------------------------------------------------*/
/* ST - RXD missing | Tality - "event_enable" - 1.6.1 */
#define PAC_RXD_EVENT_ENABLE__AGGREND_RESPONDBA_MA_0          PAC_RXD_EVENT_ENABLE__RX_EVENT_00
#define PAC_RXD_EVENT_ENABLE__AGGREND_RESPONDBA_MA_1          PAC_RXD_EVENT_ENABLE__RX_EVENT_01
#define PAC_RXD_EVENT_ENABLE__AGGREND                         PAC_RXD_EVENT_ENABLE__RX_EVENT_02
#define PAC_RXD_EVENT_ENABLE__FRAME_ABORT                     PAC_RXD_EVENT_ENABLE__RX_EVENT_03
#define PAC_RXD_EVENT_ENABLE__CRC_ERROR                       PAC_RXD_EVENT_ENABLE__RX_EVENT_04
#define PAC_RXD_EVENT_ENABLE__RESERVED_1                      PAC_RXD_EVENT_ENABLE__RX_EVENT_05
#define PAC_RXD_EVENT_ENABLE__CTS                             PAC_RXD_EVENT_ENABLE__RX_EVENT_06
#define PAC_RXD_EVENT_ENABLE__RTS_MA_0                        PAC_RXD_EVENT_ENABLE__RX_EVENT_07
#define PAC_RXD_EVENT_ENABLE__RTS_MA_1                        PAC_RXD_EVENT_ENABLE__RX_EVENT_08
#define PAC_RXD_EVENT_ENABLE__BAR_IMM_MA_0                    PAC_RXD_EVENT_ENABLE__RX_EVENT_09
#define PAC_RXD_EVENT_ENABLE__BAR_IMM_MA_1                    PAC_RXD_EVENT_ENABLE__RX_EVENT_10
#define PAC_RXD_EVENT_ENABLE__BAR_DELAYED_NOACK               PAC_RXD_EVENT_ENABLE__RX_EVENT_11
#define PAC_RXD_EVENT_ENABLE__BA_IMM                          PAC_RXD_EVENT_ENABLE__RX_EVENT_12
#define PAC_RXD_EVENT_ENABLE__BA_DELAYED_NOACK                PAC_RXD_EVENT_ENABLE__RX_EVENT_13
#define PAC_RXD_EVENT_ENABLE__BSS_BEACON                      PAC_RXD_EVENT_ENABLE__RX_EVENT_14
#define PAC_RXD_EVENT_ENABLE__MULTICAST_PKT                   PAC_RXD_EVENT_ENABLE__RX_EVENT_15
#define PAC_RXD_EVENT_ENABLE__QOSDATA_NOACK                   PAC_RXD_EVENT_ENABLE__RX_EVENT_16
#define PAC_RXD_EVENT_ENABLE__ACK_RECD_SEND_NEXT_DATA         PAC_RXD_EVENT_ENABLE__RX_EVENT_17
#define PAC_RXD_EVENT_ENABLE__RESERVED_2                      PAC_RXD_EVENT_ENABLE__RX_EVENT_18
#define PAC_RXD_EVENT_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_RXD_EVENT_ENABLE__RX_EVENT_19
#define PAC_RXD_EVENT_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_RXD_EVENT_ENABLE__RX_EVENT_20
#define PAC_RXD_EVENT_ENABLE__QOSDATA_CLEARNAV                PAC_RXD_EVENT_ENABLE__RX_EVENT_21
#define PAC_RXD_EVENT_ENABLE__CFEND_RECD_CLEARNAV             PAC_RXD_EVENT_ENABLE__RX_EVENT_22
#define PAC_RXD_EVENT_ENABLE__NOT_FOR_US_UPDATENAV            PAC_RXD_EVENT_ENABLE__RX_EVENT_23

#define PAC_RXD_EVENT_ENABLE__ALTERNATE_LINK                  PAC_RXD_EVENT_ENABLE__RX_EVENT_24

#define PAC_RXD_EVENT_ENABLE__UPDATE_SSN_BAB                  PAC_RXD_EVENT_ENABLE__RX_EVENT_25_BAB
#define PAC_RXD_EVENT_ENABLE__UPDATE_ACK_BITMAP_BAB           PAC_RXD_EVENT_ENABLE__RX_EVENT_26_BAB

#define PAC_RXD_EVENT_ENABLE__HT_RTS_FRAME                    PAC_RXD_EVENT_ENABLE__RX_EVENT_27_DUR
#define PAC_RXD_EVENT_ENABLE__HTC_DATA_TRQ_NDP                PAC_RXD_EVENT_ENABLE__RX_EVENT_28_DUR
#define PAC_RXD_EVENT_ENABLE__HTC_MGMT_TRQ_NDP                PAC_RXD_EVENT_ENABLE__RX_EVENT_29_DUR
#define PAC_RXD_EVENT_ENABLE__HTC_CTRL_WRAPPER_TRQ_NDP        PAC_RXD_EVENT_ENABLE__RX_EVENT_30_DUR

#if 0 // RX_BUFFER_FULL_NOT_RESPONSE_ACK

#define  PAC_RXD_EVENT_ENABLE__BSS_NO_RESP            \
    ( PAC_RXD_EVENT_ENABLE__AGGREND                  \
    | PAC_RXD_EVENT_ENABLE__FRAME_ABORT              \
    | PAC_RXD_EVENT_ENABLE__CRC_ERROR                \
    | PAC_RXD_EVENT_ENABLE__CTS                      \
    | PAC_RXD_EVENT_ENABLE__BAR_DELAYED_NOACK        \
    | PAC_RXD_EVENT_ENABLE__BA_IMM                   \
    | PAC_RXD_EVENT_ENABLE__BA_DELAYED_NOACK         \
    | PAC_RXD_EVENT_ENABLE__MULTICAST_PKT            \
    | PAC_RXD_EVENT_ENABLE__QOSDATA_NOACK            \
    | PAC_RXD_EVENT_ENABLE__ACK_RECD_SEND_NEXT_DATA  \
    | PAC_RXD_EVENT_ENABLE__QOSDATA_CLEARNAV         \
    | PAC_RXD_EVENT_ENABLE__CFEND_RECD_CLEARNAV      \
    | PAC_RXD_EVENT_ENABLE__NOT_FOR_US_UPDATENAV     \
    | PAC_RXD_EVENT_ENABLE__ALTERNATE_LINK           \
    | PAC_RXD_EVENT_ENABLE__UPDATE_SSN_BAB           \
    | PAC_RXD_EVENT_ENABLE__UPDATE_ACK_BITMAP_BAB ) 
#else
#define PAC_RXD_EVENT_ENABLE__BSS_NO_RESP            \
    ( PAC_RXD_EVENT_ENABLE__AGGREND                  \
    | PAC_RXD_EVENT_ENABLE__CRC_ERROR                \
    | PAC_RXD_EVENT_ENABLE__CTS                      \
    | PAC_RXD_EVENT_ENABLE__BAR_DELAYED_NOACK        \
    | PAC_RXD_EVENT_ENABLE__BA_IMM                   \
    | PAC_RXD_EVENT_ENABLE__BA_DELAYED_NOACK         \
    | PAC_RXD_EVENT_ENABLE__MULTICAST_PKT            \
    | PAC_RXD_EVENT_ENABLE__QOSDATA_NOACK            \
    | PAC_RXD_EVENT_ENABLE__ACK_RECD_SEND_NEXT_DATA  \
    | PAC_RXD_EVENT_ENABLE__QOSDATA_CLEARNAV         \
    | PAC_RXD_EVENT_ENABLE__CFEND_RECD_CLEARNAV      \
    | PAC_RXD_EVENT_ENABLE__NOT_FOR_US_UPDATENAV     \
    | PAC_RXD_EVENT_ENABLE__ALTERNATE_LINK           \
    | PAC_RXD_EVENT_ENABLE__UPDATE_SSN_BAB           \
    | PAC_RXD_EVENT_ENABLE__UPDATE_ACK_BITMAP_BAB )

#endif

#define PAC_RXD_EVENT_ENABLE__MA_0                         \
    ( PAC_RXD_EVENT_ENABLE__AGGREND_RESPONDBA_MA_0         \
    | PAC_RXD_EVENT_ENABLE__RTS_MA_0                       \
    | PAC_RXD_EVENT_ENABLE__BAR_IMM_MA_0                   \
    | PAC_RXD_EVENT_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_0 )

#define PAC_RXD_EVENT_ENABLE__MA_1                         \
    ( PAC_RXD_EVENT_ENABLE__AGGREND_RESPONDBA_MA_1         \
    | PAC_RXD_EVENT_ENABLE__RTS_MA_1                       \
    | PAC_RXD_EVENT_ENABLE__BAR_IMM_MA_1                   \
    | PAC_RXD_EVENT_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_1 )

#define PAC_RXD_EVENT_ENABLE__DISABLE_ALL               0

/* ----------------------------------------------------------------*/
/* ST - RXD missing | Tality - "rx_enable" - 1.6.2 */
#define PAC_RXD_RX_ENABLE__AGGREND_RESPONDBA_MA_0          PAC_RXD_RX_ENABLE__RX_EVENT_00
#define PAC_RXD_RX_ENABLE__AGGREND_RESPONDBA_MA_1          PAC_RXD_RX_ENABLE__RX_EVENT_01
#define PAC_RXD_RX_ENABLE__AGGREND                         PAC_RXD_RX_ENABLE__RX_EVENT_02
#define PAC_RXD_RX_ENABLE__FRAME_ABORT                     PAC_RXD_RX_ENABLE__RX_EVENT_03
#define PAC_RXD_RX_ENABLE__CRC_ERROR                       PAC_RXD_RX_ENABLE__RX_EVENT_04
#define PAC_RXD_RX_ENABLE__RESERVED_1                      PAC_RXD_RX_ENABLE__RX_EVENT_05
#define PAC_RXD_RX_ENABLE__CTS                             PAC_RXD_RX_ENABLE__RX_EVENT_06
#define PAC_RXD_RX_ENABLE__RTS_MA_0                        PAC_RXD_RX_ENABLE__RX_EVENT_07
#define PAC_RXD_RX_ENABLE__RTS_MA_1                        PAC_RXD_RX_ENABLE__RX_EVENT_08
#define PAC_RXD_RX_ENABLE__BAR_IMM_MA_0                    PAC_RXD_RX_ENABLE__RX_EVENT_09
#define PAC_RXD_RX_ENABLE__BAR_IMM_MA_1                    PAC_RXD_RX_ENABLE__RX_EVENT_10
#define PAC_RXD_RX_ENABLE__BAR_DELAYED_NOACK               PAC_RXD_RX_ENABLE__RX_EVENT_11
#define PAC_RXD_RX_ENABLE__BA_IMM                          PAC_RXD_RX_ENABLE__RX_EVENT_12
#define PAC_RXD_RX_ENABLE__BA_DELAYED_NOACK                PAC_RXD_RX_ENABLE__RX_EVENT_13
#define PAC_RXD_RX_ENABLE__BSS_BEACON                      PAC_RXD_RX_ENABLE__RX_EVENT_14
#define PAC_RXD_RX_ENABLE__MULTICAST_PKT                   PAC_RXD_RX_ENABLE__RX_EVENT_15
#define PAC_RXD_RX_ENABLE__QOSDATA_NOACK                   PAC_RXD_RX_ENABLE__RX_EVENT_16
#define PAC_RXD_RX_ENABLE__ACK_RECD_SEND_NEXT_DATA         PAC_RXD_RX_ENABLE__RX_EVENT_17
#define PAC_RXD_RX_ENABLE__RESERVED_2                      PAC_RXD_RX_ENABLE__RX_EVENT_18
#define PAC_RXD_RX_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_RXD_RX_ENABLE__RX_EVENT_19
#define PAC_RXD_RX_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_RXD_RX_ENABLE__RX_EVENT_20
#define PAC_RXD_RX_ENABLE__QOSDATA_CLEARNAV                PAC_RXD_RX_ENABLE__RX_EVENT_21
#define PAC_RXD_RX_ENABLE__CFEND_RECD_CLEARNAV             PAC_RXD_RX_ENABLE__RX_EVENT_22
#define PAC_RXD_RX_ENABLE__NOT_FOR_US_UPDATENAV            PAC_RXD_RX_ENABLE__RX_EVENT_23
#define PAC_RXD_RX_ENABLE__UNRECOGNISEDRX                  PAC_RXD_RX_ENABLE__RX_EVENT_UNRECOGNISEDRX  // PAC doc desc: Discard or retain on no-match

#define PAC_RXD_RX_ENABLE__DEFAULT_VALUE                 \
    | PAC_RXD_RX_ENABLE__RTS_MA_0                        \
    | PAC_RXD_RX_ENABLE__RTS_MA_1                        \
    | PAC_RXD_RX_ENABLE__BAR_IMM_MA_0                    \
    | PAC_RXD_RX_ENABLE__BAR_IMM_MA_1                    \
    | PAC_RXD_RX_ENABLE__BAR_DELAYED_NOACK               \
    | PAC_RXD_RX_ENABLE__BA_IMM                          \
    | PAC_RXD_RX_ENABLE__BA_DELAYED_NOACK                \
    | PAC_RXD_RX_ENABLE__BSS_BEACON                      \
    | PAC_RXD_RX_ENABLE__MULTICAST_PKT                   \
    | PAC_RXD_RX_ENABLE__QOSDATA_NOACK                   \
    | PAC_RXD_RX_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_0  \
    | PAC_RXD_RX_ENABLE__UNICAST_PKT_RECD_SEND_ACK_MA_1  )

#define PAC_RXD_RX_ENABLE__DISABLE_ALL                0


/* ----------------------------------------------------------------*/
/* Pattern Matcher Condition/Filter match values */
/* Condition A */
#define PAC_RXD_BFILTER__ACK                            PAC_RXF_BYTE_FILTER_00__MATCH
#define PAC_RXD_BFILTER__CTS                            PAC_RXF_BYTE_FILTER_01__MATCH
#define PAC_RXD_BFILTER__RTS                            PAC_RXF_BYTE_FILTER_02__MATCH
#define PAC_RXD_BFILTER__CF_END                         PAC_RXF_BYTE_FILTER_03__MATCH
#define PAC_RXD_BFILTER__BAR                            PAC_RXF_BYTE_FILTER_04__MATCH
#define PAC_RXD_BFILTER__BA                             PAC_RXF_BYTE_FILTER_05__MATCH
#define PAC_RXD_BFILTER__BEACON                         PAC_RXF_BYTE_FILTER_06__MATCH
#define PAC_RXD_BFILTER__QOSDATA                        PAC_RXF_BYTE_FILTER_07__MATCH
#define PAC_RXD_BFILTER__POLL_BIT                       PAC_RXF_BYTE_FILTER_08__MATCH
#define PAC_RXD_BFILTER__NULL_BIT                       PAC_RXF_BYTE_FILTER_09__MATCH
#define PAC_RXD_BFILTER__DATA_BIT                       PAC_RXF_BYTE_FILTER_10__MATCH
#define PAC_RXD_BFILTER__MCAST                          PAC_RXF_BYTE_FILTER_11__MATCH
#define PAC_RXD_BFILTER__BA_CTRL_NO_ACK                 PAC_RXF_BYTE_FILTER_12__MATCH
#define PAC_RXD_BFILTER__QOS_CTRL_NORMAL_ACK_MISMATCH   PAC_RXF_BYTE_FILTER_13__MATCH    //mismatch (INV reg set)
#define PAC_RXD_BFILTER__DURATION_LOW_ZERO              PAC_RXF_BYTE_FILTER_14__MATCH
#define PAC_RXD_BFILTER__DURATION_HIGH_ZERO             PAC_RXF_BYTE_FILTER_15__MATCH
#define PAC_RXD_BFILTER__CONTROL_WRAPPER                PAC_RXF_BYTE_FILTER_16__MATCH
#define PAC_RXD_BFILTER__HT_MODE                        PAC_RXF_BYTE_FILTER_17__MATCH
#define PAC_RXD_BFILTER__ORDER_BIT                      PAC_RXF_BYTE_FILTER_18__MATCH  // Order Bit 1
#define PAC_RXD_BFILTER__HTC_DATA_TRQ                   PAC_RXF_BYTE_FILTER_19__MATCH  // DATA FRAME TRQ=1
#define PAC_RXD_BFILTER__HTC_DATA_NDP                   PAC_RXF_BYTE_FILTER_20__MATCH  // FATA FRAME NDP=0
#define PAC_RXD_BFILTER__HTC_CTRL_WRAPPER_TRQ           PAC_RXF_BYTE_FILTER_21__MATCH  // CTRL WRAPPER FRAME TRQ=1
#define PAC_RXD_BFILTER__HTC_CTRL_WRAPPER_NDP           PAC_RXF_BYTE_FILTER_22__MATCH  // CTRL WRAPPER FRAME NDP=0

#define PAC_RXD_BFILTER__HTC_MGMT_TRQ                   PAC_RXF_BYTE_FILTER_23__MATCH  // MGMT FRAME TRQ=1
#define PAC_RXD_BFILTER__HTC_MGMT_NDP                   PAC_RXF_BYTE_FILTER_24__MATCH  // MGMT FRAME NDP=0
#define PAC_RXD_BFILTER__MGMT                           PAC_RXF_BYTE_FILTER_25__MATCH  // MGMT FRAMES
#define PAC_RXD_BFILTER__HT_AGGREGATION                 PAC_RXF_BYTE_FILTER_26__MATCH

#define PAC_RXD_LFILTER__A1_OWNMAC_0                    PAC_RXF_LONG_BYTE_FILTER_0__MATCH
#define PAC_RXD_LFILTER__A3_BSSID_IBSSONLY              PAC_RXF_LONG_BYTE_FILTER_1__MATCH
#define PAC_RXD_LFILTER__A1_OWNMAC_1                    PAC_RXF_LONG_BYTE_FILTER_2__MATCH
#define PAC_RXD_SP_FILTER__TATID                        PAC_RXF_TATID_FILTER__MATCH
#define PAC_RXD_SP_FILTER__END_OF_AGGR                  PAC_RXF_END_OF_AGGR_0_FILTER__MATCH
#define PAC_RXD_SP_FILTER__NORMAL_ACK_IN_AGG            PAC_RXF_NORMAL_ACK_IN_AGG_0_FILTER__MATCH
#if 1 // (ASIC_1250_CUT_1 && SUPPORT_MULTI_MAC_ADDR)
#define PAC_RXD_LFILTER__A1_OWNMAC                      PAC_RXF_LONG_BYTE_FILTER_0_OR_2__MATCH
#else
#define PAC_RXD_LFILTER__A1_OWNMAC                      PAC_RXF_LONG_BYTE_FILTER_0__MATCH
#endif
#define PAC_RXD_SP_FILTER__FRAME_ABORT                  PAC_RXF_FRAME_ABORT_FILTER__MATCH
#define PAC_RXD_SP_FILTER__CRC_ERROR                    PAC_RXF_RX_CRC_ERROR__MATCH
/* Condition B */
#define PAC_RXD_SP_FILTER__END_OF_AGGR_MISMATCH         PAC_RXF_END_OF_AGGR_1_FILTER__MATCH
#define PAC_RXD_SP_FILTER__IN_AGGR_MATCH                PAC_RXF_WITHIN_AGGR_0_FILTER__MATCH

/* ----------------------------------------------------------------*/
/* Receive filter registers */
#define PAC_RXF_BYTE_FILTER_ACK                             PAC_RXF_BYTE_FILTER_CONTROL_0
#define PAC_RXF_BYTE_FILTER_CTS                             PAC_RXF_BYTE_FILTER_CONTROL_1
#define PAC_RXF_BYTE_FILTER_RTS                             PAC_RXF_BYTE_FILTER_CONTROL_2
#define PAC_RXF_BYTE_FILTER_CF_END                          PAC_RXF_BYTE_FILTER_CONTROL_3
#define PAC_RXF_BYTE_FILTER_BAR                             PAC_RXF_BYTE_FILTER_CONTROL_4
#define PAC_RXF_BYTE_FILTER_BA                              PAC_RXF_BYTE_FILTER_CONTROL_5
#define PAC_RXF_BYTE_FILTER_BEACON                          PAC_RXF_BYTE_FILTER_CONTROL_6
#define PAC_RXF_BYTE_FILTER_QOSDATA                         PAC_RXF_BYTE_FILTER_CONTROL_7
#define PAC_RXF_BYTE_FILTER_POLL_BIT                        PAC_RXF_BYTE_FILTER_CONTROL_8
#define PAC_RXF_BYTE_FILTER_NULL_BIT                        PAC_RXF_BYTE_FILTER_CONTROL_9
#define PAC_RXF_BYTE_FILTER_DATA_BIT                        PAC_RXF_BYTE_FILTER_CONTROL_10
#define PAC_RXF_BYTE_FILTER_MCAST                           PAC_RXF_BYTE_FILTER_CONTROL_11
#define PAC_RXF_BYTE_FILTER_BA_CTRL_NO_ACK                  PAC_RXF_BYTE_FILTER_CONTROL_12
#define PAC_RXF_BYTE_FILTER_QOS_CTRL_NORMAL_ACK_MISMATCH    PAC_RXF_BYTE_FILTER_CONTROL_13    //mismatch (INV reg set)
#define PAC_RXF_BYTE_FILTER_DURATION_LOW_ZERO               PAC_RXF_BYTE_FILTER_CONTROL_14
#define PAC_RXF_BYTE_FILTER_DURATION_HIGH_ZERO              PAC_RXF_BYTE_FILTER_CONTROL_15
#define PAC_RXF_BYTE_FILTER_CONTROL_WRAPPER                 PAC_RXF_BYTE_FILTER_CONTROL_16
#define PAC_RXF_BYTE_FILTER_HT_MODE                         PAC_RXF_BYTE_FILTER_CONTROL_17
#define PAC_RXF_BYTE_FILTER_ORDER_BIT                       PAC_RXF_BYTE_FILTER_CONTROL_18
#define PAC_RXF_BYTE_FILTER_HTC_DATA_TRQ                    PAC_RXF_BYTE_FILTER_CONTROL_19
#define PAC_RXF_BYTE_FILTER_HTC_DATA_NDP                    PAC_RXF_BYTE_FILTER_CONTROL_20
#define PAC_RXF_BYTE_FILTER_HTC_CTRL_WRAPPER_TRQ            PAC_RXF_BYTE_FILTER_CONTROL_21
#define PAC_RXF_BYTE_FILTER_HTC_CTRL_WRAPPER_NDP            PAC_RXF_BYTE_FILTER_CONTROL_22
#define PAC_RXF_BYTE_FILTER_HTC_MGMT_TRQ                    PAC_RXF_BYTE_FILTER_CONTROL_23
#define PAC_RXF_BYTE_FILTER_HTC_MGMT_NDP                    PAC_RXF_BYTE_FILTER_CONTROL_24
#define PAC_RXF_BYTE_FILTER_MGMT                            PAC_RXF_BYTE_FILTER_CONTROL_25
#define PAC_RXF_BYTE_FILTER_HT_AGGREGATION                  PAC_RXF_BYTE_FILTER_CONTROL_26


#define PAC_RXF_LFILTER_A1_OWNMAC_0_CTL                     PAC_RXF_LONG_FILTER_0_CONTROL
#define PAC_RXF_LFILTER_A1_OWNMAC_0_REF_1                   PAC_RXF_LONG_FILTER_0_REF1
#define PAC_RXF_LFILTER_A1_OWNMAC_0_REF_2                   PAC_RXF_LONG_FILTER_0_REF2
#define PAC_RXF_LFILTER_A3_BSSID_IBSSONLY_CTL               PAC_RXF_LONG_FILTER_1_CONTROL
#define PAC_RXF_LFILTER_A3_BSSID_IBSSONLY_REF_1             PAC_RXF_LONG_FILTER_1_REF1
#define PAC_RXF_LFILTER_A3_BSSID_IBSSONLY_REF_2             PAC_RXF_LONG_FILTER_1_REF2
#define PAC_RXF_LFILTER_A1_OWNMAC_1_CTL                     PAC_RXF_LONG_FILTER_2_CONTROL
#define PAC_RXF_LFILTER_A1_OWNMAC_1_REF_1                   PAC_RXF_LONG_FILTER_2_REF1
#define PAC_RXF_LFILTER_A1_OWNMAC_1_REF_2                   PAC_RXF_LONG_FILTER_2_REF2
#define PAC_RXF_LFILTER_A2_TA_CTL                           PAC_RXF_LONG_FILTER_3_CONTROL
#define PAC_RXF_LFILTER_A2_TA_REF_1                         PAC_RXF_LONG_FILTER_3_REF1
#define PAC_RXF_LFILTER_A2_TA_REF_2                         PAC_RXF_LONG_FILTER_3_REF2
/* ----------------------------------------------------------------*/
/* Receive event decoder registers */
#define PAC_RXD_CONDITION_AGGREND_RESPONDBA_MA_0           PAC_RXD_CONDITION_0
#define PAC_RXD_CONDITIONB_AGGREND_RESPONDBA_MA_0          PAC_RXD_CONDITIONB_0

#define PAC_RXD_CONDITION_AGGREND_RESPONDBA_MA_1           PAC_RXD_CONDITION_1
#define PAC_RXD_CONDITIONB_AGGREND_RESPONDBA_MA_1          PAC_RXD_CONDITIONB_1

#define PAC_RXD_CONDITION_AGGREND                          PAC_RXD_CONDITION_2
#define PAC_RXD_CONDITIONB_AGGREND                         PAC_RXD_CONDITIONB_2

#define PAC_RXD_CONDITION_FRAME_ABORT                      PAC_RXD_CONDITION_3
#define PAC_RXD_CONDITIONB_FRAME_ABORT                     PAC_RXD_CONDITIONB_3

#define PAC_RXD_CONDITION_CRC_ERROR                        PAC_RXD_CONDITION_4
#define PAC_RXD_CONDITIONB_CRC_ERROR                       PAC_RXD_CONDITIONB_4

#define PAC_RXD_CONDITION_RESERVED_1                       PAC_RXD_CONDITION_5
#define PAC_RXD_CONDITIONB_RESERVED_1                      PAC_RXD_CONDITIONB_5

#define PAC_RXD_CONDITION_CTS                              PAC_RXD_CONDITION_6
#define PAC_RXD_CONDITIONB_CTS                             PAC_RXD_CONDITIONB_6

#define PAC_RXD_CONDITION_RTS_MA_0                         PAC_RXD_CONDITION_7
#define PAC_RXD_CONDITIONB_RTS_MA_0                        PAC_RXD_CONDITIONB_7

#define PAC_RXD_CONDITION_RTS_MA_1                         PAC_RXD_CONDITION_8
#define PAC_RXD_CONDITIONB_RTS_MA_1                        PAC_RXD_CONDITIONB_8

#define PAC_RXD_CONDITION_BAR_IMM_MA_0                     PAC_RXD_CONDITION_9
#define PAC_RXD_CONDITIONB_BAR_IMM_MA_0                    PAC_RXD_CONDITIONB_9

#define PAC_RXD_CONDITION_BAR_IMM_MA_1                     PAC_RXD_CONDITION_10
#define PAC_RXD_CONDITIONB_BAR_IMM_MA_1                    PAC_RXD_CONDITIONB_10

#define PAC_RXD_CONDITION_BAR_DELAYED_NOACK                PAC_RXD_CONDITION_11
#define PAC_RXD_CONDITIONB_BAR_DELAYED_NOACK               PAC_RXD_CONDITIONB_11

#define PAC_RXD_CONDITION_BA_IMM                           PAC_RXD_CONDITION_12
#define PAC_RXD_CONDITIONB_BA_IMM                          PAC_RXD_CONDITIONB_12

#define PAC_RXD_CONDITION_BA_DELAYED_NOACK                 PAC_RXD_CONDITION_13
#define PAC_RXD_CONDITIONB_BA_DELAYED_NOACK                PAC_RXD_CONDITIONB_13

#define PAC_RXD_CONDITION_BSS_BEACON                       PAC_RXD_CONDITION_14
#define PAC_RXD_CONDITIONB_BSS_BEACON                      PAC_RXD_CONDITIONB_14

#define PAC_RXD_CONDITION_MULTICAST_PKT                    PAC_RXD_CONDITION_15
#define PAC_RXD_CONDITIONB_MULTICAST_PKT                   PAC_RXD_CONDITIONB_15

#define PAC_RXD_CONDITION_QOSDATA_NOACK                    PAC_RXD_CONDITION_16
#define PAC_RXD_CONDITIONB_QOSDATA_NOACK                   PAC_RXD_CONDITIONB_16

#define PAC_RXD_CONDITION_ACK_RECD_SEND_NEXT_DATA          PAC_RXD_CONDITION_17
#define PAC_RXD_CONDITIONB_ACK_RECD_SEND_NEXT_DATA         PAC_RXD_CONDITIONB_17

#define PAC_RXD_CONDITION_RESERVED_2                       PAC_RXD_CONDITION_18
#define PAC_RXD_CONDITIONB_RESERVED_2                      PAC_RXD_CONDITIONB_18

#define PAC_RXD_CONDITION_UNICAST_PKT_RECD_SEND_ACK_MA_0   PAC_RXD_CONDITION_19
#define PAC_RXD_CONDITIONB_UNICAST_PKT_RECD_SEND_ACK_MA_0  PAC_RXD_CONDITIONB_19

#define PAC_RXD_CONDITION_UNICAST_PKT_RECD_SEND_ACK_MA_1   PAC_RXD_CONDITION_20
#define PAC_RXD_CONDITIONB_UNICAST_PKT_RECD_SEND_ACK_MA_1  PAC_RXD_CONDITIONB_20

#define PAC_RXD_CONDITION_QOSDATA_CLEARNAV                 PAC_RXD_CONDITION_21
#define PAC_RXD_CONDITIONB_QOSDATA_CLEARNAV                PAC_RXD_CONDITIONB_21

#define PAC_RXD_CONDITION_CFEND_RECD_CLEARNAV              PAC_RXD_CONDITION_22
#define PAC_RXD_CONDITIONB_CFEND_RECD_CLEARNAV             PAC_RXD_CONDITIONB_22

#define PAC_RXD_CONDITION_NOT_FOR_US_UPDATENAV             PAC_RXD_CONDITION_23
#define PAC_RXD_CONDITIONB_NOT_FOR_US_UPDATENAV            PAC_RXD_CONDITIONB_23

/* Any RX-event qualified will be fed to HT-table selection (PAC_RXD_HT_ROW_ENABLE) and
 * ALT-table selection (PAC_RXD_AMP_ROW_ENABLE).
 * RX events 0-24 are selected for NTD. The highest priority (lowest number) RX event (0-24)
 * wins the selection and is fed to NTD.
 * So we can assign PAC_RXD_CONDITION_ALT_LINK to PAC_RXD_CONDITION_24.
*/
#define PAC_RXD_CONDITION_ALT_LINK                         PAC_RXD_CONDITION_24
#define PAC_RXD_CONDITIONB_ALT_LINK                        PAC_RXD_CONDITIONB_24

#define PAC_RXD_CONDITION_UPDATE_SSN_BAB                   PAC_RXD_CONDITION_25
#define PAC_RXD_CONDITIONB_UPDATE_SSN_BAB                  PAC_RXD_CONDITIONB_25

#define PAC_RXD_CONDITION_UPDATE_ACK_BITMAP_BAB            PAC_RXD_CONDITION_26
#define PAC_RXD_CONDITIONB_UPDATE_ACK_BITMAP_BAB           PAC_RXD_CONDITIONB_26

// New DUR for CW1200 Cut2 only, not seen by NTD
#define PAC_RXD_CONDITION__ALT_RESP_RATE_HT_RTS            PAC_RXD_CONDITION_27
#define PAC_RXD_CONDITIONB__ALT_RESP_RATE_HT_RTS           PAC_RXD_CONDITIONB_27

#define PAC_RXD_CONDITION__ALT_RESP_RATE_HTC_DATA_TRQ_NDP  PAC_RXD_CONDITION_28
#define PAC_RXD_CONDITIONB__ALT_RESP_RATE_HTC_DATA_TRQ_NDP PAC_RXD_CONDITIONB_28

#define PAC_RXD_CONDITION__ALT_RESP_RATE_HTC_MGMT_TRQ_NDP  PAC_RXD_CONDITION_29
#define PAC_RXD_CONDITIONB__ALT_RESP_RATE_HTC_MGMT_TRQ_NDP PAC_RXD_CONDITIONB_29

#define PAC_RXD_CONDITION__ALT_RESP_RATE_HTC_CTRL_WRAPPER_TRQ_NDP  PAC_RXD_CONDITION_30
#define PAC_RXD_CONDITIONB__ALT_RESP_RATE_HTC_CTRL_WRAPPER_TRQ_NDP PAC_RXD_CONDITIONB_30

#endif    //#ifndef PAC_DEFS_WLAN_H
